.localhistory/WebApplication3/Controllers/1485881942$QAController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication3.Controllers
{
    public class QAController : Controller
    {
        //
        // GET: /QA/

        public ActionResult Index()
        {
            return View();
        }

    }
}

.localhistory/WebApplication3/Views/QA/1486063002$QAIndex.cshtml
@model WebApplication3.Models.ViewModel.QuestionDataView
@{
    ViewBag.Title = "QAIndex";
}
<script type="text/javascript">
  
        //document.getElementById("display").onclick = function myFunction(indec)
        //{ console.log(indec); };

        function DisplayQuestion(i) {
            console.log("hello" + i);

            $.ajax({
                type: "POST",
                url: @Url.Action("PostAnswer","QA"),
                    success: function (data) {
                        //alert(data);
                        if (data == 1) {
                            tmp = true;
                        }
                        else {
                            tmp = false;
                        }
                    }
            });
        }
        
   
</script>
<div class="divide30"></div>

<div class="container main-qa">
    <div class="row">
        <div class="col-xs-1"></div>
        <div class="col-xs-3">
            <a href="/QA/PostQuestion" class="btn btn btn-theme-dark"> <i class="fa fa-plus"></i>&nbsp;NEW QUESTION</a>
        </div>
        <div class="col-xs-7 tabs">
            <ul class="QA nav nav-tabs">
            <li class="active" role="presentation"><a href="#">NEWEST</a></li>
            <li role="presentation"><a href="#">FREQUENT</a></li>
            <li role="presentation"><a href="#">VOTES</a></li>
            <li role="presentation"><a href="#">ACTIVE</a></li>
            <li role="presentation"><a href="#">UNANSWERED</a></li>
            </ul>
        </div>
    </div>
    <hr/>
    <div class="divide30"></div>

    @{int index = 0;}
    <div class="qa-post-titles">
        <div class="col-sm-1"></div>
        <div class="col-sm-10">
             @foreach (var i in Model.Questions)
             {
                if(index % 2==0)
                {
                    <div class="row">
                        <div class="col-sm-1"></div>
                         <div class="col-sm-7 ">
                            <div class="row">
                                 <div class="col-sm-12 qa-title">
                                    @{int QA_id=i.QuestionId;}
                                  <a href="#" onclick='DisplayQuestion(@QA_id); return false'>@Html.DisplayFor(m => i.Subject)</a>
                                </div>
                            </div>
                            <div class="row ">
                                <div class="col-sm-12 qa-content">
                                    @Html.Raw(Server.HtmlDecode(i.Content))
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-3 qa-details">
                            <div class="row">
                                <div class="col-sm-3">
                                    [ICON]
                                </div>
                                <div class="col-sm-9">
                                    <div class="col-sm-12">
                                         @Html.DisplayFor(m => i.QuestionAuthor)
                                    </div>
                                    <div class="col-sm-12">
                                         posted on @Html.DisplayFor(m => i.PostedDate)
                                    </div>
                                </div>
                            </div>
                        </div>
                   </div>
                }
                else{
                    <div class="row" style="background-color: #eef2f4;">
                        <div class="col-sm-1"></div>
                        <div class="col-sm-7 ">
                            <div class="row">
                                 <div class="col-sm-12 qa-title">
                                     @{int QA_id=i.QuestionId;}
                                  <a href="#" onclick='DisplayQuestion(@QA_id)'>@Html.DisplayFor(m => i.Subject)</a>
                                </div>
                            </div>
                            <div class="row ">
                                <div class="col-sm-12 qa-content">
                                    @Html.Raw(Server.HtmlDecode(i.Content))
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-3 qa-details">
                            <div class="row">
                                <div class="col-sm-3">
                                    [ICON]
                                </div>
                                <div class="col-sm-9">
                                    <div class="col-sm-12">
                                         @Html.DisplayFor(m => i.QuestionAuthor)
                                    </div>
                                    <div class="col-sm-12">
                                         posted on @Html.DisplayFor(m => i.PostedDate)
                                    </div>
                                </div>
                            </div>
                        </div>
                   </div>
                }
                index++;
            }
        </div>
      <div class="col-sm-1"></div>
    </div>

</div>

.localhistory/WebApplication3/Views/QA/1486398673$PostAnswer.cshtml
@{
    ViewBag.Title = "PostAnswer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>PostAnswer</h2>
<div class="divide30"></div>


<div class="container">
    <h4>Question</h4>
    <div class="row">
        <div class="col-sm-1"></div>
        <div class="col-sm-10 answer-quest">
            <div class="col-sm-10">
                <div class="row ">
                    <div class="col-sm-1">vote</div>
                    <div class="col-sm-8">
                        <div class="row">question title</div>
                        <div class="row">question content</div>
                    </div>
                    <div class="col-sm-3">question details</div>
                </div>
            </div>
        </div>
        <div class="col-sm-1"></div>    
    </div>
    <hr />
    <h4>Answers</h4>
    <div class="row">
        <div class="col-sm-1"></div>
        <div class="col-sm-10 answers">
            <div class="col-sm-10">
                <div class="row ">
                    <div class="col-sm-1">vote</div>
                    <div class="col-sm-8">
                        <div class="row">answer title</div>
                        <div class="row">answer content</div>
                    </div>
                    <div class="col-sm-3">answer details</div>
                </div>
            </div>
        </div>
        <div class="col-sm-1"></div>    
    </div>

    <hr />
    
    <h4>Post Answer</h4>
    <form method="post" >
        <div class="divide20"></div>
        <div class="row">
            <div class="col-sm-1"></div>
            <div class="col-xs-10">
                <div class="AnswerContent"></div>
            </div>
        </div>
    
        <div class="divide20"></div>
        <div class="row final-buttons">
            <div class="col-sm-1"></div>
           <div class="col-xs-10">
                <a href="#" class="btn border-black">Preview</a>
                <div id="SubmitQuestion" class="btn btn-theme-bg">
                    <btn onclick="SubmitAnswer" >Submit </btn>
                </div>
            </div>
        </div>  
    </form>
</div>

<div class="divide30"></div>

<script type="text/javascript">
    $('document').ready(function () {
        textboxio.replaceAll('.AnswerContent');

        document.getElementById('SubmitAnswer').onclick = function () {
            // Get the active editor
            var editor = textboxio.getActiveEditor();
            // Retrieve the contents of the active editor
            var content = editor.content.get();
            console.log(content);

@*                $.ajax({
                    type: "POST",
                    url: '@(Url.Action("PostAnswerToDb", "QA"))',
                    data: {'qa_content': content },
                success: function (apiResult) {
                    location.href = "/QA/PostAnswer";
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    alert("jhj" + textStatus);
                }
                });
            *@
            
        };
    });
</script>

.localhistory/WebApplication3/Views/QA/1486400455$PostAnswer.cshtml
@model WebApplication3.Models.ViewModel.QuestionAnswer
@{
    ViewBag.Title = "PostAnswer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>PostAnswer</h2>
<div class="divide30"></div>


<div class="container">
    <h4>Question</h4>
    <div class="row">
        <div class="col-sm-1"></div>
        <div class="col-sm-10 answer-quest">
            <div class="col-sm-10">
                <div class="row ">
                    <div class="col-sm-1">vote</div>
                    <div class="col-sm-8">
                        <div class="row">@Model.Subject</div>
                        <div class="row">@Model.Content</div>
                    </div>
                    <div class="col-sm-3">
                        <div class="row">
                            <div class="col-sm-3">
                                [ICON]
                            </div>
                            <div class="col-sm-9">
                                <div class="col-sm-12">
                                        @Model.QuestionAuthor
                                </div>
                                <div class="col-sm-12">
                                        @Model.PostedDate
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-1"></div>    
    </div>
    <hr />
    <h4>Answers</h4>
    <div class="row">
        <div class="col-sm-1"></div>
        <div class="col-sm-10 answers">
            <div class="col-sm-10">
                <div class="row ">
                    <div class="col-sm-1">vote</div>
                    <div class="col-sm-8">
                        <div class="row">answer title</div>
                        <div class="row">answer content</div>
                    </div>
                    <div class="col-sm-3">answer details</div>
                </div>
            </div>
        </div>
        <div class="col-sm-1"></div>    
    </div>

    <hr />
    
    <h4>Post Answer</h4>
    <form method="post" >
        <div class="divide20"></div>
        <div class="row">
            <div class="col-sm-1"></div>
            <div class="col-xs-10">
                <div class="AnswerContent"></div>
            </div>
        </div>
    
        <div class="divide20"></div>
        <div class="row final-buttons">
            <div class="col-sm-1"></div>
           <div class="col-xs-10">
                <a href="#" class="btn border-black">Preview</a>
                <div id="SubmitQuestion" class="btn btn-theme-bg">
                    <btn onclick="SubmitAnswer" >Submit </btn>
                </div>
            </div>
        </div>  
    </form>
</div>

<div class="divide30"></div>

<script type="text/javascript">
    $('document').ready(function () {
        textboxio.replaceAll('.AnswerContent');

        document.getElementById('SubmitAnswer').onclick = function () {
            // Get the active editor
            var editor = textboxio.getActiveEditor();
            // Retrieve the contents of the active editor
            var content = editor.content.get();
            console.log(content);

@*                $.ajax({
                    type: "POST",
                    url: '@(Url.Action("PostAnswerToDb", "QA"))',
                    data: {'qa_content': content },
                success: function (apiResult) {
                    location.href = "/QA/PostAnswer";
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    alert("jhj" + textStatus);
                }
                });
            *@
            
        };
    });
</script>

.localhistory/WebApplication3/Views/QA/1486405251$PostAnswer.cshtml
@model WebApplication3.Models.ViewModel.QuestionAnswer
@{
    ViewBag.Title = "PostAnswer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>PostAnswer</h2>
<div class="divide30"></div>


<div class="container">
    <h4>Question</h4>
    <div class="row">
        <div class="col-sm-1"></div>
        <div class="col-sm-10 answer-quest">
           <div class="row ">
               <div class="col-sm-1">@Model.Answers.Count() Answers</div>
                <div class="col-sm-8">
                    <div class="row ">@Model.Subject</div>
                    <div class="row qa-content">@Model.Content</div>
                </div>
                <div class="col-sm-3">
                    <div class="row">
                        <div class="col-sm-3">
                            [ICON]
                        </div>
                        <div class="col-sm-9">
                            <div class="col-sm-12">
                                    @Model.QuestionAuthor
                            </div>
                            <div class="col-sm-12">
                                    posted on @Model.PostedDate
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-1"></div>    
    </div>
    <hr />
    <h4>Answers</h4>
    
    @foreach (var i in Model.Answers)
    {
        <div class="row">
            <div class="col-sm-1"></div>
            <div class="col-sm-10 answers">
                <div class="row ">
                    <div class="col-sm-8">
                        <div class="row"> @Html.Raw(Server.HtmlDecode(i.Content))</div>
                    </div>
                    <div class="col-sm-4">
                            <div class="row">
                            <div class="col-sm-3">
                                [ICON]
                            </div>
                            <div class="col-sm-9">
                                <div class="col-sm-12">
                                        @Html.DisplayFor(m => i.AnswerAuthor)
                                </div>
                                <div class="col-sm-12">
                                        posted on @Html.DisplayFor(m => i.PostedDate)
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }

    <hr />
    
    <h4>Post Answer</h4>
    <form method="post" >
        <div class="divide20"></div>
        <div class="row">
            <div class="col-sm-1"></div>
            <div class="col-xs-10">
                <div class="AnswerContent"></div>
            </div>
        </div>
    
        <div class="divide20"></div>
        <div class="row final-buttons">
            <div class="col-sm-1"></div>
           <div class="col-xs-10">
                <a href="#" class="btn border-black">Preview</a>
                <div id="SubmitAnswer" class="btn btn-theme-bg">
                    <btn onclick="SubmitAnswer" >Submit </btn>
                </div>
            </div>
        </div>  
    </form>
</div>

<div class="divide30"></div>

<script type="text/javascript">
    $('document').ready(function () {
        textboxio.replaceAll('.AnswerContent');

        document.getElementById('SubmitAnswer').onclick = function () {
            // Get the active editor
            var editor = textboxio.getActiveEditor();
            // Retrieve the contents of the active editor
            var content = editor.content.get();
            var x = '@Model.QuestionId';
            console.log(x);
            var qa_data = { 'content': content, 'qid': x };

                $.ajax({
                    type: "POST",
                    url: '@(Url.Action("PostAnswerToDb", "QA"))',
                    data: { qa_content: content,q_id: x },
                    success: function (apiResult) {
                        console.log(apiResult);
                       // qid = parseInt(apiResult);
                        
                        location.href = '@(Url.Action("PostAnswer", "QA",new {Qid=@Model.QuestionId}))';
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    alert("jhj" + textStatus);
                }
                });
            
            
        };
    });
</script>

.localhistory/WebApplication3/Views/QA/1486405472$PostAnswer.cshtml
@model WebApplication3.Models.ViewModel.QuestionAnswer
@{
    ViewBag.Title = "PostAnswer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>PostAnswer</h2>
<div class="divide30"></div>


<div class="container">
    <h4>Question</h4>
    <div class="row">
        <div class="col-sm-1"></div>
        <div class="col-sm-10 answer-quest">
           <div class="row ">
               <div class="col-sm-1">
                   <div class="">@Model.Answers.Count()</div> 
                   <div class="">Answers</div>
               </div>
                <div class="col-sm-8">
                    <div class="row ">@Model.Subject</div>
                    <div class="row qa-content">@Model.Content</div>
                </div>
                <div class="col-sm-3">
                    <div class="row">
                        <div class="col-sm-3">
                            [ICON]
                        </div>
                        <div class="col-sm-9">
                            <div class="col-sm-12">
                                    @Model.QuestionAuthor
                            </div>
                            <div class="col-sm-12">
                                    posted on @Model.PostedDate
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-1"></div>    
    </div>
    <hr />
    <h4>Answers</h4>
    
    @foreach (var i in Model.Answers)
    {
        <div class="row">
            <div class="col-sm-1"></div>
            <div class="col-sm-10 answers">
                <div class="row ">
                    <div class="col-sm-8">
                        <div class="row"> @Html.Raw(Server.HtmlDecode(i.Content))</div>
                    </div>
                    <div class="col-sm-4">
                            <div class="row">
                            <div class="col-sm-3">
                                [ICON]
                            </div>
                            <div class="col-sm-9">
                                <div class="col-sm-12">
                                        @Html.DisplayFor(m => i.AnswerAuthor)
                                </div>
                                <div class="col-sm-12">
                                        posted on @Html.DisplayFor(m => i.PostedDate)
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }

    <hr />
    
    <h4>Post Answer</h4>
    <form method="post" >
        <div class="divide20"></div>
        <div class="row">
            <div class="col-sm-1"></div>
            <div class="col-xs-10">
                <div class="AnswerContent"></div>
            </div>
        </div>
    
        <div class="divide20"></div>
        <div class="row final-buttons">
            <div class="col-sm-1"></div>
           <div class="col-xs-10">
                <a href="#" class="btn border-black">Preview</a>
                <div id="SubmitAnswer" class="btn btn-theme-bg">
                    <btn onclick="SubmitAnswer" >Submit </btn>
                </div>
            </div>
        </div>  
    </form>
</div>

<div class="divide30"></div>

<script type="text/javascript">
    $('document').ready(function () {
        textboxio.replaceAll('.AnswerContent');

        document.getElementById('SubmitAnswer').onclick = function () {
            // Get the active editor
            var editor = textboxio.getActiveEditor();
            // Retrieve the contents of the active editor
            var content = editor.content.get();
            var x = '@Model.QuestionId';
            console.log(x);
            var qa_data = { 'content': content, 'qid': x };

                $.ajax({
                    type: "POST",
                    url: '@(Url.Action("PostAnswerToDb", "QA"))',
                    data: { qa_content: content,q_id: x },
                    success: function (apiResult) {
                        console.log(apiResult);
                       // qid = parseInt(apiResult);
                        
                        location.href = '@(Url.Action("PostAnswer", "QA",new {Qid=@Model.QuestionId}))';
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    alert("jhj" + textStatus);
                }
                });
            
            
        };
    });
</script>

.localhistory/WebApplication3/Views/QA/1486481816$PostAnswer.cshtml
@model WebApplication3.Models.ViewModel.QuestionAnswer
@{
    ViewBag.Title = "PostAnswer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="divide30"></div>


<div class="container">
    <h4>Question</h4>
    <div class="row">
        <div class="col-sm-1"></div>
        <div class="col-sm-10 answer-quest">
           <div class="row ">
               <div class="col-sm-1">
                   <div class="answers-number">@Model.Answers.Count()</div> 
                   <div class="answers-text">Answers</div>
               </div>
                <div class="col-sm-7">
                    <div class="row ans-title">@Model.Subject</div>
                    <div class="row ans-content">@Model.Content</div>
                </div>
                <div class="col-sm-4">
                    <div class="row">
                        <div class="col-sm-3">
                            [ICON]
                        </div>
                        <div class="col-sm-9 ans-details">
                            <div class="col-sm-12">
                                   Asked by: @Model.QuestionAuthor
                            </div>
                            <div class="col-sm-12">
                                    Posted on: @Model.PostedDate
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-1"></div>    
    </div>
    <hr />
    <h4>Answers</h4>
    
    @foreach (var i in Model.Answers)
    {
        <div class="row">
            <div class="col-sm-1"></div>
            <div class="col-sm-10 answers">
                <div class="row ">
                    <div class="col-sm-8">
                        <div class="row ans-content"> @Html.Raw(Server.HtmlDecode(i.Content))</div>
                    </div>
                    <div class="col-sm-4">
                            <div class="row">
                            <div class="col-sm-3">
                                [ICON]
                            </div>
                            <div class="col-sm-9 ans-details">
                                <div class="col-sm-12">
                                        Answered by: @Html.DisplayFor(m => i.AnswerAuthor)
                                </div>
                                <div class="col-sm-12">
                                        Posted on: @Html.DisplayFor(m => i.PostedDate)
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }

    <hr />
    
    <h4>Post Answer</h4>
    <form method="post" >
        <div class="divide20"></div>
        <div class="row">
            <div class="col-sm-1"></div>
            <div class="col-xs-10">
                <div class="AnswerContent"></div>
            </div>
        </div>
    
        <div class="divide20"></div>
        <div class="row final-buttons">
            <div class="col-sm-1"></div>
           <div class="col-xs-10">
               <div id="SubmitAnswer" class="btn btn-theme-bg">
                    <btn onclick="SubmitAnswer" >Submit </btn>
                </div>
                <a href="/QA/Cancel" class="btn border-black">Cancel</a>
             </div>
        </div>  
    </form>
</div>

<div class="divide30"></div>

<script type="text/javascript">
    $('document').ready(function () {
        textboxio.replaceAll('.AnswerContent');

        document.getElementById('SubmitAnswer').onclick = function () {
            // Get the active editor
            var editor = textboxio.getActiveEditor();
            // Retrieve the contents of the active editor
            var content = editor.content.get();
            var x = '@Model.QuestionId';
            console.log(x);
            var qa_data = { 'content': content, 'qid': x };

                $.ajax({
                    type: "POST",
                    url: '@(Url.Action("PostAnswerToDb", "QA"))',
                    data: { qa_content: content,q_id: x },
                    success: function (apiResult) {
                        console.log(apiResult);
                       // qid = parseInt(apiResult);
                        
                        location.href = '@(Url.Action("PostAnswer", "QA",new {Qid=@Model.QuestionId}))';
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    alert("jhj" + textStatus);
                }
                });
            
            
        };
    });
</script>

.localhistory/WebApplication3/Views/QA/1486485877$PostAnswer.cshtml
@model WebApplication3.Models.ViewModel.QuestionAnswer
@{
    ViewBag.Title = "PostAnswer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script type="text/javascript">
    $(document).ready(function () {
        console.log('@(TempData["Value"])');

        if ('@(TempData["Value"])' == 1) {
            console.log("error");
            $('#signin-required-modal').modal("show");
        }
    });



</script>
<div class="divide30"></div>


<div class="container">
    <h4>Question</h4>
    <div class="row">
        <div class="col-sm-1"></div>
        <div class="col-sm-10 answer-quest">
           <div class="row ">
               <div class="col-sm-1">
                   <div class="answers-number">@Model.Answers.Count()</div> 
                   <div class="answers-text">Answers</div>
               </div>
                <div class="col-sm-7">
                    <div class="row ans-title">@Model.Subject</div>
                    <div class="row ans-content">@Model.Content</div>
                </div>
                <div class="col-sm-4">
                    <div class="row">
                        <div class="col-sm-3">
                            [ICON]
                        </div>
                        <div class="col-sm-9 ans-details">
                            <div class="col-sm-12">
                                   Asked by: @Model.QuestionAuthor
                            </div>
                            <div class="col-sm-12">
                                    Posted on: @Model.PostedDate
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-1"></div>    
    </div>
    <hr />
    <h4>Answers</h4>
    
    @foreach (var i in Model.Answers)
    {
        <div class="row">
            <div class="col-sm-1"></div>
            <div class="col-sm-10 answers">
                <div class="row ">
                    <div class="col-sm-8">
                        <div class="row ans-content"> @Html.Raw(Server.HtmlDecode(i.Content))</div>
                    </div>
                    <div class="col-sm-4">
                            <div class="row">
                            <div class="col-sm-3">
                                [ICON]
                            </div>
                            <div class="col-sm-9 ans-details">
                                <div class="col-sm-12">
                                        Answered by: @Html.DisplayFor(m => i.AnswerAuthor)
                                </div>
                                <div class="col-sm-12">
                                        Posted on: @Html.DisplayFor(m => i.PostedDate)
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }

    <hr />
    
    <h4>Post Answer</h4>
    <form method="post" >
        <div class="divide20"></div>
        <div class="row">
            <div class="col-sm-1"></div>
            <div class="col-xs-10">
                <div class="AnswerContent"></div>
            </div>
        </div>
    
        <div class="divide20"></div>
        <div class="row final-buttons">
            <div class="col-sm-1"></div>
           <div class="col-xs-10">
               <div id="SubmitAnswer" class="btn btn-theme-bg">
                    <btn onclick="SubmitAnswer" >Submit </btn>
                </div>
                <a href="/QA/QAIndex" class="btn border-black">Cancel</a>
             </div>
        </div>  
    </form>
</div>

<div class="divide30"></div>

<script type="text/javascript">
    $('document').ready(function () {
        textboxio.replaceAll('.AnswerContent');

        document.getElementById('SubmitAnswer').onclick = function () {
            // Get the active editor
            var editor = textboxio.getActiveEditor();
            // Retrieve the contents of the active editor
            var content = editor.content.get();
            var x = '@Model.QuestionId';
            console.log(x);
            var qa_data = { 'content': content, 'qid': x };

                $.ajax({
                    type: "POST",
                    url: '@(Url.Action("PostAnswerToDb", "QA"))',
                    data: { qa_content: content,q_id: x },
                    success: function (apiResult) {
                        console.log(apiResult);
                       // qid = parseInt(apiResult);
                        
                        location.href = '@(Url.Action("PostAnswer", "QA",new {Qid=@Model.QuestionId}))';
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    alert("jhj" + textStatus);
                }
                });
            
            
        };
    });
</script>